import { Music, Play, Pause, Volume2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ContributorAvatars } from "@/components/ContributorAvatars";
import Navbar from "@/components/Navbar";

const MusicPage = () => {
  const contributors = ["Jeni", "Karthik", "Rishaban","Bhuvaneshwaran", "Chiranjeevi","Thamilavan", "Harish"];
  
  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <main className="pt-20 pb-12">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="flex items-center justify-center w-20 h-20 bg-gradient-primary rounded-xl mb-6 mx-auto animate-glow">
              <Music className="w-10 h-10 text-white" />
            </div>
            <h1 className="text-5xl font-bold bg-gradient-primary bg-clip-text text-transparent mb-4">
              AI Music 
            </h1>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Enjoy exclusive tracks created with the power of artificial intelligence.
            </p>
          </div>
          

          {/* Demo Area */}
          <div className="glass-dark rounded-xl p-8 border border-white/20">
            <h2 className="text-2xl font-bold text-foreground mb-6">Demo</h2>
            
            {/* Audio Player UI */}
            <div className="bg-gradient-primary/10 rounded-lg p-6 mb-6 border border-white/20">
              <div className="flex items-center justify-between mb-4">
                <div>
                  <h3 className="text-lg font-semibold text-foreground">AI Generated Symphony #1</h3>
                  <p className="text-sm text-muted-foreground">Generated by AI</p>
                </div>
                <Volume2 className="w-6 h-6 text-primary" />
              </div>
              
              <div className="flex items-center space-x-4">
                <Button variant="gradient" size="sm" className="rounded-full">
                  <Play className="w-4 h-4" />
                </Button>
                <div className="flex-1 bg-muted/30 rounded-full h-2">
                  <div className="bg-gradient-primary h-2 rounded-full w-1/3"></div>
                </div>
                <span className="text-sm text-muted-foreground">1:15 / 3:42</span>
              </div>
            </div>

            {/* Generation Controls
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-3">Generate New Music</h3>
                <div className="space-y-3">
                  <div>
                    <label className="text-sm text-foreground block mb-1">Genre</label>
                    <select className="w-full bg-muted/30 border border-white/20 rounded-lg p-2 text-foreground">
                      <option>Classical</option>
                      <option>Jazz</option>
                      <option>Electronic</option>
                      <option>Rock</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-sm text-foreground block mb-1">Mood</label>
                    <select className="w-full bg-muted/30 border border-white/20 rounded-lg p-2 text-foreground">
                      <option>Uplifting</option>
                      <option>Melancholic</option>
                      <option>Energetic</option>
                      <option>Peaceful</option>
                    </select>
                  </div>
                  <Button variant="gradient" className="w-full">
                    Generate Music
                  </Button>
                </div>
              </div>
              
              <div>
                <h3 className="text-lg font-semibold text-foreground mb-3">Recent Generations</h3>
                <div className="space-y-2">
                  {["Jazz Improvisation #3", "Electronic Beat #7", "Classical Waltz #2"].map((track, index) => (
                    <div key={track} className="flex items-center justify-between p-3 bg-muted/20 rounded-lg">
                      <span className="text-sm text-foreground">{track}</span>
                      <Button variant="ghost" size="sm">
                        <Play className="w-3 h-3" />
                      </Button>
                    </div>
                  ))}
                </div>
              </div>
            </div> */}
          </div>

          {/* Contributors */}
          <div className="glass-dark rounded-xl p-6 mt-8 mb-8 border border-white/20">
            <h2 className="text-xl font-semibold text-foreground mb-4">Contributors</h2>
            <ContributorAvatars contributors={contributors} />
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mt-5">
              {contributors.map((contributor, index) => (
                <div key={contributor} className="text-center">
                  <div className="w-16 h-16 bg-gradient-to-br from-purple-500 to-pink-500 rounded-full mx-auto mb-2 flex items-center justify-center text-white font-bold text-lg">
                    {contributor.charAt(0)}
                  </div>
                  <p className="text-sm font-medium text-foreground">{contributor}</p>
                </div>
              ))}
            </div>
          </div>
        </div>

      </main>
    </div>
  );
};

export default MusicPage;